### PR TITLE
Sidebar

### PR DESCRIPTION
**Pull request by aoki-marika**
Adds a sidebar to regular horizontal size classes to replace the tab bar.

For simplicity's sake this removes `Main.storyboard` and splits it into individual self-contained storyboards, the base interface once connected to a server is now handled programmatically.

Simulator Screen Shot - iPad Air (5th generation) - 2022-09-05 at 22 50 22
Simulator Screen Shot - iPad Air (5th generation) - 2022-09-05 at 22 51 45

 - [x] Relies on #12

### CODE REVIEW

**Comment by aoki-marika** [comment]
The SwiftUI implementation is currently functional but a bit rough around the edges, such as the sidebar toggle button creating a secondary navigation bar on top of the tab:
Screen Shot 2022-09-13 at 1 13 55 AM

As noted in the commits moving this to SwiftUI is necessary to continue moving in this direction, sticking with the UIKit implementation breaks any hopes of seamless SwiftUI integration which further hinders the SwiftUI interfaces that have to be hacked into UIKit and lose a lot of their versatility.

I don't want to make this PR any larger than it already is converting the existing navigation bars to SwiftUI proxies to eliminate this, so I propose ignoring this problem for now and waiting to publish the next version until the interface redesign is complete.

**Comment by dannylin0711** [comment]
I think SwiftUI conversion needs lots of effort to do, maybe we should open another branch for SwiftUI and slowly transition to it?

**Comment by aoki-marika** [comment]
I would definitely agree with that, I'm not sure why I didn't consider it in the first place.

It does feel a bit hacky and messy at the moment trying to implement SwiftUI into the existing application, moving the migration to a separate branch would allow me to slowly add back each existing feature without trying to maintain compatibility. Then once it is feature equal to the existing interface it could be merged back and pushed to testers and users or otherwise. This would also allow me to create smaller, easier to review pull requests as there doesn't have to be compatibility layers and internal changes interwoven with each PR. I do apologize for the size of these PRs making them a chore to review.

If @rodepanda could create a `swiftui` branch I will close this pull request and begin the migration there anew, creating pull requests to that branch instead.

**Comment by rodepanda** [comment]
Branch created.

**Pull request closed without merging**
