### PR TITLE
Mirroring 2nd style

### PR DESCRIPTION
**Pull request by aoki-marika**
Simulator Screen Shot - iPad Air (4th generation) - 2022-08-21 at 07 18 01

This contains large changes to the mirroring system to better improve the experience, and work around the limitations of Spice as best we can:

### Client-side touch indicators

The amount of latency from Spice to SpiceCompanion is enough that touches feel unresponsive, despite touches actually performing near-instantly, due to the visual feedback. This adds the "touch indicators" that you see on the server to SpiceCompanion, allowing them to display instantly and smoothly, which singlehandedly improves the experience by a great margin and helps the latency of the screen not feel so noticeable.

### Appearance changes

Some minor adjustments were made to the appearance of the screen, moving the navigation bar to a toolbar, enforcing dark mode on the controller, and hiding things like the status bar and home indicator.

### Metal-based rendering

`UIImageView` is slow and complex for this use case, so it is now replaced by Metal and CoreImage rendering. This uses much less battery, does not heat up the device, and slightly improves the latency. Although almost all of the latency comes from the server capturing the screen and sending it, improvements in SpiceCompanion's rendering can give us the best results possible given the situation.

### Internal changes

Naturally with this the internal structure of `MirrorViewController` and its subsystems have changed, moving towards more encapsulation and separation of logic with more clearly-defined handlers for each task. Essentially "Model View Controller" instead of "Massive View Controller".

### Afterword

In the future this will be further expanded upon with settings for disabling touch indicators, mirror alignment options, and more visual flare, but as for now I felt this was a good point to propose the changes and see where this project intends to go in terms of its own future, or how much should be moved to a fork. Generally I would like to go through and revamp every aspect of the application, but perhaps that's not in the scope of this project and I should move it to my own fork. Please do feel free to leave contact information or directly provide feedback on the topic here so it can be discussed further, if that is necessary.

- [x] Built off of and thus relies on #7

### CODE REVIEW

**Comment by rodepanda** [comment]
Thank you for the commit again. You can contact me through Discord: rodepanda#1637

**Review by rodepanda — APPROVED** [review]

**Comment by dannylin0711** [comment]
This PR seem to broke touch position and rendering on 4:3 iPads, for touch position, the touch point and the real response in the game have an Y-axis offset. And for the rendering, the bottom part of the screen is chopped off, both main screen and sub screen.

**Comment by dannylin0711** [comment]
7BBCD16C-3BCE-4EA4-A8D7-71E1F2A6FF54
4D454386-4BFD-4D55-8554-00DB96254021

**Comment by aoki-marika** [comment]
I discovered this issue earlier, I had come across it during testing and thought I had fixed it already but it seems not. Working on a hotfix at the moment.

**Pull request merged**
